export const tables = [
  { id: 1, isReserved: false },
  { id: 2, isReserved: true },
  { id: 3, isReserved: false },
  { id: 4, isReserved: false },
  { id: 5, isReserved: true },
  { id: 6, isReserved: false },
  { id: 7, isReserved: false },
  { id: 8, isReserved: true },
  { id: 9, isReserved: false },
  { id: 10, isReserved: false },
  { id: 11, isReserved: true },
  { id: 12, isReserved: false },
  { id: 13, isReserved: false },
  { id: 14, isReserved: true },
  { id: 15, isReserved: false },
  { id: 16, isReserved: false },
  { id: 17, isReserved: true },
  { id: 18, isReserved: false },
  { id: 19, isReserved: true },
  { id: 20, isReserved: false },
];