import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/header";
import { CartProvider } from "./_contexts/cart";
import AuthProvider from "./_providers/auth";
import { Analytics } from "@vercel/analytics/react"
import { Toaster } from "./_components/ui/sonner";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s | Tempero Tech",
    default: "Tempero Tech",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CartProvider>
            <div className="space-y-8">
              <Header />
              <div className="pt-6">{children}</div>
            </div>
          </CartProvider>
        </AuthProvider>
        <Toaster />
        <Analytics />
      </body>
    </html>
  );
}
